/**
 * @file app-token.js
 *
 * This is an auto generated token for app authentication. Any changes here will
 * be overridden. However, if you wish to set the app token manually modify the
 * plugin configuration in the `plugin.json`.
 * Check the documentation for more information.
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 *
 * IMPORTANT: THIS FILE IS AUTO GENERATED, CHANGES MAY BE OVERRIDDEN!
 */

module.exports = 'da9ca4a0-14bf-11eb-b063-1b8df9e4f59c';
